name: stugio60.ch
recipe: wordpress
proxy:
  appserver:
    - stugio60.ch.lndo.site
    - stugio60site2.ch.lndo.site
    - stugio60site3.ch.lndo.site
  phpmyadmin:
    - phpmyadmin.stugio60.ch.lndo.site
config:
  php: "8.1"
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  xdebug: true
  config:
    php: config/php.ini
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
